exclude: ['vendor']
include: ['_pages']

title:            TakeRefuge
email:            imsbb2018@imslbb.org
url:              http://www.take-refuge.com
paginate:         5
paginate_path:    archive/page:num/
author:
  name:           Bootblack Teagan
  twitter:        https://twitter.com/imsbb2018

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Teagan is IMsBB 2018. During her title year she encourage people to "Take Refuge"
  at the bootblack stand.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.take-refuge.com" # the base hostname & protocol for your site
# twitter_username: twidx
# github_username:  tkwidmer

tag_page: '/blog/tags/'
category_page: '/blog/categories/'

collections:
  galleries:
    output: true

# Build settings
pages: ./_pages
markdown: kramdown

# pages_list:
#   Programming: '/pages/programming.html'
#   Speaking:   '/pages/speaking.html'
#   Blog: '/blog.html'
#   Feed: '/feed.xml'

# social_links:
#   - icon: fa-twitter
#     url: http://www.twitter.com/twidx
#   - icon: fa-github
#     url: http://www.github.com/tkwidmer

gems:
  - jekyll-redirect-from

header-img: "images/sf1.jpg"
